config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Avo::Engine, at: Avo.configuration.root_path

  # Defines the root path route ("/")
  root "illustrations#index"

  resources :illustrations, only: %i(index) do
    get :search, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/illustration.rb
class Illustration < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: :slugged
  acts_as_taggable_on :tags

  has_one_attached :svg

  validates :name, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true
  validates :svg, attached: true, content_type: "image/svg+xml",
                                  size: {
                                    less_than_or_equal_to: 100.kilobytes,
                                    message: :size_less_than_or_equal_to
                                  },
                                  on: :create
  validate :tags_blank

  scope :search, -> (q) do
    q = q.to_s
    where("LOWER(illustrations.name) LIKE ?", "%#{q.downcase}%")
      .or(where(id: search_by_tags(q).ids))
      .distinct
  end

  scope :search_by_tags, ->(q) do
    tagged_with(
      q.is_a?(Array) ? q : [q.to_s],
      on: :tags,
      wild: true,
      any: true
    )
  end

  private

  def tags_blank
    return unless tag_list.compact_blank.blank?

    errors.add(:tags, :blank)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avo/illustrations_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::IllustrationsController < Avo::ResourcesController
  private

  def model_params
    processed_params = super

    processed_params.each do |key, val|
      next if key.to_sym != :tags || val.blank?

      processed_params[:tags] = JSON.parse(val).map do |tag|
        tag.values.first
      end.join(",")
    end

    processed_params
  end
end

app/controllers/avo/taggings_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::TaggingsController < Avo::ResourcesController
end

app/controllers/avo/tags_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::TagsController < Avo::ResourcesController
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  def index
    @illustrations = Illustration.all

    if (q = search_params[:q]).present?
      @illustrations = @illustrations.search(q)
    elsif search_params.key?(:q)
      @illustrations = []
    end
  end

  def search; end

  private

  def search_params
    params.permit(:q)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(field, opts = {})
    svg = field.try(:value) || field
    Rails.cache.fetch ["svg", "file", svg.attachment.filename, svg.record.updated_at.to_i, opts.to_s] do
      svg_tag(svg.download, opts)
    end
  end

  def svg_tag(file, opts = {})
    content =
      if file.is_a?(Tempfile)
        file.read
      elsif file.is_a?(String) && file.end_with?(".svg")
        file = Rails.root.join("app", "assets", "images", file).to_s
        File.read(file) if File.exist?(file)
      else
        file
      end
    svg = Nokogiri::HTML::DocumentFragment.parse(content).at_css('svg')
    opts.each { |attr, value| svg[attr.to_s] = value }

    svg.to_html.html_safe
  end

  def cache_key(purpose, illustration)
    [
      purpose,
      illustration.slug,
      illustration.id,
      illustration.svg.attachment.filename,
      illustration.updated_at.to_i,
    ]
  end

  def display_name(illustration)
    Rails.cache.fetch cache_key(:name, illustration) do
      illustration.name.titleize
    end
  end

  def display_tags(illustration)
    Rails.cache.fetch cache_key(:tags, illustration) do
      illustration.tag_list.join(", ")
    end
  end
end

app/helpers/illustrations_helper.rb
module IllustrationsHelper
end

app/views/illustrations/_thumbnail.html.erb
<div>
  <div class="aspect-[280/200] bg-zinc-100 rounded-xl overflow-hidden flex items-center justify-center">
    <%= render_svg(illustration.svg, width: "70%", height: "70%", class: "object-cover", alt: display_name(illustration)) %>
  </div>
  <div>
    <div class="inline-flex items-center justify-between w-full px-4">
      <div>
        <h2
          class="text-base font-semibold text-black dark:text-white mt-8 relative"
        >
          <%= display_name(illustration) %>
        </h2>
        <p
          class="relative z-10 mt-2 text-sm text-zinc-500 dark:text-zinc-400"
        >
          <%= display_tags(illustration) %>
        </p>
      </div>
      <div class="mt-4 hidden">
        <a
          class="group inline-flex items-center justify-center rounded-lg py-2 px-4 text-sm font-semibold focus:outline-none focus-visible:outline-2 focus-visible:outline-offset-2 bg-zinc-900 text-white hover:bg-zinc-700 hover:text-zinc-100 active:bg-zinc-800 active:text-zinc-300 focus-visible:outline-zinc-900 dark:bg-white dark:text-black"
          href="#">...</a
        >
      </div>
    </div>
  </div>
</div>

app/views/illustrations/index.html.erb
<% if @illustrations.any? %>
  <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-x-3 gap-y-12 p-4">
    <%= render partial: "thumbnail", collection: @illustrations, as: :illustration %>
  </div>
<% else %>
  <div class="mt-12 ml-6">
    <h1
      class="text-black dark:text-white text-xl md:text-2xl lg:text-4xl xl:text-6xl font-bold tracking-tighter"
    >
      <% if params[:q].blank? %>
        No search keyword!
      <% else %>
        No illustrations found with name or tags using <span class="underline"><%= params[:q] %></span>
      <% end %>
    </h1>
  </div>
<% end %>

<% if params.key?(:q) %>
  <div class="my-4 ml-6">
    <%= link_to search_illustrations_path, class: "group inline-flex items-center justify-center rounded-lg py-2 px-4 text-sm font-semibold focus:outline-none focus-visible:outline-2 focus-visible:outline-offset-2 bg-zinc-900 text-white hover:bg-zinc-700 hover:text-zinc-100 active:bg-zinc-800 active:text-zinc-300 focus-visible:outline-zinc-900 dark:bg-white dark:text-black" do %>
      <span>Search Again</span>
    <% end %>
  </div>
<% end %>

app/views/illustrations/search.html.erb
<div class="p-6 mt-6">
  <div class="mb-4">
    <h1
      class="text-black dark:text-white text-2xl md:text-4xl lg:text-6xl xl:text-8xl font-bold tracking-tighter"
    >
      Search
    </h1>
  </div>
  <%= form_with url: illustrations_path, method: :get, local: true do |form| %>
    <%= form.search_field :q, required: true, placeholder: "Hit enter key to search", class: "w-1/2 p-3 text-white dark:text-black bg-black dark:bg-white text-md md:text-lg lg:text-xl xl:text-2xl tracking-tighter rounded-xl" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>/illustrations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="author" content="MarLo MoraLes" />
    <meta
      name="Illustrations"
      content="svg list,svg listing,svg,illustration,illustration list,illustration listing,/illustrations"
    />
    <meta name="msapplication-TileColor" content="#1b1d20" />
    <meta name="theme-color" content="#1b1d20" />
    <link rel="icon" href="/favicon.ico" sizes="any">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <!-- Inter Font: https://rsms.me/inter/ -->
    <link rel="preconnect" href="https://rsms.me/" />
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-white dark:bg-black">
    <div class="2xl:max-w-7xl mx-auto">
      <div class="grid grid-cols-1 lg:grid-cols-4">
        <%= render "layouts/shared/sidebar" %>
        <main role="main" class="w-full lg:col-span-3">
          <section>
            <%= yield %>
          </section>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/layouts/shared/_sidebar.html.erb
<aside class="w-full">
  <div
    class="sticky top-0 rounded-xl w-full px-8 sm:px-16 py-8 lg:py-12 lg:px-10">
    <div>
      <%= link_to root_path, class: "text-black dark:text-white" do %>
        <%= svg_tag("diamond.svg") %>
      <% end %>
    </div>
    <h1
      class="text-black dark:text-white text-xl md:text-2xl xl:text-3xl 2xl:text-5xl font-bold tracking-tighter">
      <%= link_to "/illustrations", root_path, class: "text-black dark:text-white" %>
    </h1>
    <div class="lg:mt-8 max-w-xl">
      <p class="dark:text-zinc-400 text-zinc-500 text-base">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
      </p>
    </div>
    <div class="mt-4 pt-6 border-t border-zinc-800">
      <nav>
        <ul
          class="lg:space-y-3 space-x-3 list-none no-underline mt-6 lg:mt-12 inline-flex items-center sm:flex sm:flex-col sm:items-start sm:space-x-0"
          role="list">
          <!-- <li>
            <a
              class="dark:text-zinc-400 text-zinc-500 dark:hover:text-white hover:text-black inline-flex items-center"
              href="#">
              <span> About</span>
            </a>
          </li> -->
          <li>
            <% unless current_page?(action: :search) || params.key?(:q) %>
              <%= link_to search_illustrations_path, class: "group inline-flex items-center justify-center rounded-lg py-2 px-4 text-sm font-semibold focus:outline-none focus-visible:outline-2 focus-visible:outline-offset-2 bg-zinc-900 text-white hover:bg-zinc-700 hover:text-zinc-100 active:bg-zinc-800 active:text-zinc-300 focus-visible:outline-zinc-900 dark:bg-white dark:text-black" do %>
                <span> Search</span>
              <% end %>
            <% end %>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</aside>